=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require "uri"

module SwaggerClient
  class CatalogApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Upload the full catalog as XML
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [SimplePlanJson] :body 
    # @option opts [String] :x_killbill_created_by 
    # @option opts [String] :x_killbill_reason 
    # @option opts [String] :x_killbill_comment 
    # @return [nil]
    def add_simple_plan(opts = {})
      add_simple_plan_with_http_info(opts)
      return nil
    end

    # Upload the full catalog as XML
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [SimplePlanJson] :body 
    # @option opts [String] :x_killbill_created_by 
    # @option opts [String] :x_killbill_reason 
    # @option opts [String] :x_killbill_comment 
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def add_simple_plan_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: CatalogApi.add_simple_plan ..."
      end
      # resource path
      local_var_path = "/1.0/kb/catalog/simplePlan"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])
      header_params[:'X-Killbill-CreatedBy'] = opts[:'x_killbill_created_by'] if !opts[:'x_killbill_created_by'].nil?
      header_params[:'X-Killbill-Reason'] = opts[:'x_killbill_reason'] if !opts[:'x_killbill_reason'].nil?
      header_params[:'X-Killbill-Comment'] = opts[:'x_killbill_comment'] if !opts[:'x_killbill_comment'].nil?

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'body'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CatalogApi#add_simple_plan\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve available add-ons for a given product
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :base_product_name 
    # @option opts [String] :price_list_name 
    # @return [Array<PlanDetailJson>]
    def get_available_addons(opts = {})
      data, _status_code, _headers = get_available_addons_with_http_info(opts)
      return data
    end

    # Retrieve available add-ons for a given product
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :base_product_name 
    # @option opts [String] :price_list_name 
    # @return [Array<(Array<PlanDetailJson>, Fixnum, Hash)>] Array<PlanDetailJson> data, response status code and response headers
    def get_available_addons_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: CatalogApi.get_available_addons ..."
      end
      # resource path
      local_var_path = "/1.0/kb/catalog/availableAddons"

      # query parameters
      query_params = {}
      query_params[:'baseProductName'] = opts[:'base_product_name'] if !opts[:'base_product_name'].nil?
      query_params[:'priceListName'] = opts[:'price_list_name'] if !opts[:'price_list_name'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<PlanDetailJson>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CatalogApi#get_available_addons\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve available base plans
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<PlanDetailJson>]
    def get_available_base_plans(opts = {})
      data, _status_code, _headers = get_available_base_plans_with_http_info(opts)
      return data
    end

    # Retrieve available base plans
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<PlanDetailJson>, Fixnum, Hash)>] Array<PlanDetailJson> data, response status code and response headers
    def get_available_base_plans_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: CatalogApi.get_available_base_plans ..."
      end
      # resource path
      local_var_path = "/1.0/kb/catalog/availableBasePlans"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<PlanDetailJson>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CatalogApi#get_available_base_plans\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve the catalog as JSON
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :requested_date 
    # @return [StaticCatalog]
    def get_catalog_json(opts = {})
      data, _status_code, _headers = get_catalog_json_with_http_info(opts)
      return data
    end

    # Retrieve the catalog as JSON
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :requested_date 
    # @return [Array<(StaticCatalog, Fixnum, Hash)>] StaticCatalog data, response status code and response headers
    def get_catalog_json_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: CatalogApi.get_catalog_json ..."
      end
      # resource path
      local_var_path = "/1.0/kb/catalog"

      # query parameters
      query_params = {}
      query_params[:'requestedDate'] = opts[:'requested_date'] if !opts[:'requested_date'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'StaticCatalog')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CatalogApi#get_catalog_json\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Upload the full catalog as XML
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :body 
    # @option opts [String] :x_killbill_created_by 
    # @option opts [String] :x_killbill_reason 
    # @option opts [String] :x_killbill_comment 
    # @return [nil]
    def upload_catalog_xml(opts = {})
      upload_catalog_xml_with_http_info(opts)
      return nil
    end

    # Upload the full catalog as XML
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :body 
    # @option opts [String] :x_killbill_created_by 
    # @option opts [String] :x_killbill_reason 
    # @option opts [String] :x_killbill_comment 
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def upload_catalog_xml_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: CatalogApi.upload_catalog_xml ..."
      end
      # resource path
      local_var_path = "/1.0/kb/catalog"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/xml'])
      header_params[:'X-Killbill-CreatedBy'] = opts[:'x_killbill_created_by'] if !opts[:'x_killbill_created_by'].nil?
      header_params[:'X-Killbill-Reason'] = opts[:'x_killbill_reason'] if !opts[:'x_killbill_reason'].nil?
      header_params[:'X-Killbill-Comment'] = opts[:'x_killbill_comment'] if !opts[:'x_killbill_comment'].nil?

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'body'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CatalogApi#upload_catalog_xml\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
