=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require "uri"

module SwaggerClient
  class PluginsInfoApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Retrieve the list of registered plugins
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<PluginInfoJson>]
    def get_plugins_info(opts = {})
      data, _status_code, _headers = get_plugins_info_with_http_info(opts)
      return data
    end

    # Retrieve the list of registered plugins
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<PluginInfoJson>, Fixnum, Hash)>] Array<PluginInfoJson> data, response status code and response headers
    def get_plugins_info_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PluginsInfoApi.get_plugins_info ..."
      end
      # resource path
      local_var_path = "/1.0/kb/pluginsInfo"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<PluginInfoJson>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PluginsInfoApi#get_plugins_info\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
