=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require "uri"

module SwaggerClient
  class TagDefinitionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Create a tag definition
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [TagDefinitionJson] :body 
    # @option opts [String] :x_killbill_created_by 
    # @option opts [String] :x_killbill_reason 
    # @option opts [String] :x_killbill_comment 
    # @return [nil]
    def create_tag_definition(opts = {})
      create_tag_definition_with_http_info(opts)
      return nil
    end

    # Create a tag definition
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [TagDefinitionJson] :body 
    # @option opts [String] :x_killbill_created_by 
    # @option opts [String] :x_killbill_reason 
    # @option opts [String] :x_killbill_comment 
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def create_tag_definition_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TagDefinitionsApi.create_tag_definition ..."
      end
      # resource path
      local_var_path = "/1.0/kb/tagDefinitions"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])
      header_params[:'X-Killbill-CreatedBy'] = opts[:'x_killbill_created_by'] if !opts[:'x_killbill_created_by'].nil?
      header_params[:'X-Killbill-Reason'] = opts[:'x_killbill_reason'] if !opts[:'x_killbill_reason'].nil?
      header_params[:'X-Killbill-Comment'] = opts[:'x_killbill_comment'] if !opts[:'x_killbill_comment'].nil?

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'body'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TagDefinitionsApi#create_tag_definition\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete a tag definition
    # 
    # @param tag_definition_id 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_killbill_created_by 
    # @option opts [String] :x_killbill_reason 
    # @option opts [String] :x_killbill_comment 
    # @return [nil]
    def delete_tag_definition(tag_definition_id, opts = {})
      delete_tag_definition_with_http_info(tag_definition_id, opts)
      return nil
    end

    # Delete a tag definition
    # 
    # @param tag_definition_id 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_killbill_created_by 
    # @option opts [String] :x_killbill_reason 
    # @option opts [String] :x_killbill_comment 
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def delete_tag_definition_with_http_info(tag_definition_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TagDefinitionsApi.delete_tag_definition ..."
      end
      # verify the required parameter 'tag_definition_id' is set
      if @api_client.config.client_side_validation && tag_definition_id.nil?
        fail ArgumentError, "Missing the required parameter 'tag_definition_id' when calling TagDefinitionsApi.delete_tag_definition"
      end
      if @api_client.config.client_side_validation && tag_definition_id !~ Regexp.new(/\\w+-\\w+-\\w+-\\w+-\\w+/)
        fail ArgumentError, "invalid value for 'tag_definition_id' when calling TagDefinitionsApi.delete_tag_definition, must conform to the pattern /\\w+-\\w+-\\w+-\\w+-\\w+/."
      end

      # resource path
      local_var_path = "/1.0/kb/tagDefinitions/{tagDefinitionId}".sub('{' + 'tagDefinitionId' + '}', tag_definition_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      header_params[:'X-Killbill-CreatedBy'] = opts[:'x_killbill_created_by'] if !opts[:'x_killbill_created_by'].nil?
      header_params[:'X-Killbill-Reason'] = opts[:'x_killbill_reason'] if !opts[:'x_killbill_reason'].nil?
      header_params[:'X-Killbill-Comment'] = opts[:'x_killbill_comment'] if !opts[:'x_killbill_comment'].nil?

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TagDefinitionsApi#delete_tag_definition\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve a tag definition
    # 
    # @param tag_definition_id 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :audit  (default to NONE)
    # @return [TagDefinitionJson]
    def get_tag_definition(tag_definition_id, opts = {})
      data, _status_code, _headers = get_tag_definition_with_http_info(tag_definition_id, opts)
      return data
    end

    # Retrieve a tag definition
    # 
    # @param tag_definition_id 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :audit 
    # @return [Array<(TagDefinitionJson, Fixnum, Hash)>] TagDefinitionJson data, response status code and response headers
    def get_tag_definition_with_http_info(tag_definition_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TagDefinitionsApi.get_tag_definition ..."
      end
      # verify the required parameter 'tag_definition_id' is set
      if @api_client.config.client_side_validation && tag_definition_id.nil?
        fail ArgumentError, "Missing the required parameter 'tag_definition_id' when calling TagDefinitionsApi.get_tag_definition"
      end
      if @api_client.config.client_side_validation && tag_definition_id !~ Regexp.new(/\\w+-\\w+-\\w+-\\w+-\\w+/)
        fail ArgumentError, "invalid value for 'tag_definition_id' when calling TagDefinitionsApi.get_tag_definition, must conform to the pattern /\\w+-\\w+-\\w+-\\w+-\\w+/."
      end

      # resource path
      local_var_path = "/1.0/kb/tagDefinitions/{tagDefinitionId}".sub('{' + 'tagDefinitionId' + '}', tag_definition_id.to_s)

      # query parameters
      query_params = {}
      query_params[:'audit'] = opts[:'audit'] if !opts[:'audit'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'TagDefinitionJson')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TagDefinitionsApi#get_tag_definition\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List tag definitions
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :audit  (default to NONE)
    # @return [Array<TagDefinitionJson>]
    def get_tag_definitions(opts = {})
      data, _status_code, _headers = get_tag_definitions_with_http_info(opts)
      return data
    end

    # List tag definitions
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :audit 
    # @return [Array<(Array<TagDefinitionJson>, Fixnum, Hash)>] Array<TagDefinitionJson> data, response status code and response headers
    def get_tag_definitions_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: TagDefinitionsApi.get_tag_definitions ..."
      end
      # resource path
      local_var_path = "/1.0/kb/tagDefinitions"

      # query parameters
      query_params = {}
      query_params[:'audit'] = opts[:'audit'] if !opts[:'audit'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<TagDefinitionJson>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TagDefinitionsApi#get_tag_definitions\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
