=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::NodesInfoApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NodesInfoApi' do
  before do
    # run before each test
    @instance = SwaggerClient::NodesInfoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NodesInfoApi' do
    it 'should create an instance of NodesInfoApi' do
      expect(@instance).to be_instance_of(SwaggerClient::NodesInfoApi)
    end
  end

  # unit tests for get_nodes_info
  # Retrieve all the nodes infos
  # 
  # @param [Hash] opts the optional parameters
  # @return [Array<PluginInfoJson>]
  describe 'get_nodes_info test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for trigger_node_command
  # Trigger a node command
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [NodeCommandJson] :body 
  # @option opts [BOOLEAN] :local_node_only 
  # @option opts [String] :x_killbill_created_by 
  # @option opts [String] :x_killbill_reason 
  # @option opts [String] :x_killbill_comment 
  # @return [nil]
  describe 'trigger_node_command test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
