=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PaymentTransactionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentTransactionsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PaymentTransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentTransactionsApi' do
    it 'should create an instance of PaymentTransactionsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PaymentTransactionsApi)
    end
  end

  # unit tests for create_custom_fields
  # Add custom fields to payment transaction
  # 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<CustomFieldJson>] :body 
  # @option opts [String] :x_killbill_created_by 
  # @option opts [String] :x_killbill_reason 
  # @option opts [String] :x_killbill_comment 
  # @return [nil]
  describe 'create_custom_fields test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_tags
  # Add tags to payment transaction
  # 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tag_list 
  # @option opts [String] :x_killbill_created_by 
  # @option opts [String] :x_killbill_reason 
  # @option opts [String] :x_killbill_comment 
  # @return [nil]
  describe 'create_tags test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_custom_fields
  # Remove custom fields from payment transaction
  # 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :custom_field_list 
  # @option opts [String] :x_killbill_created_by 
  # @option opts [String] :x_killbill_reason 
  # @option opts [String] :x_killbill_comment 
  # @return [nil]
  describe 'delete_custom_fields test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_tags
  # Remove tags from payment transaction
  # 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tag_list 
  # @option opts [String] :x_killbill_created_by 
  # @option opts [String] :x_killbill_reason 
  # @option opts [String] :x_killbill_comment 
  # @return [nil]
  describe 'delete_tags test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_custom_fields
  # Retrieve payment transaction custom fields
  # 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :audit 
  # @return [Array<CustomFieldJson>]
  describe 'get_custom_fields test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payment_by_transaction_id
  # Retrieve a payment by transaction id
  # 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :with_plugin_info 
  # @option opts [BOOLEAN] :with_attempts 
  # @option opts [Array<String>] :plugin_property 
  # @option opts [String] :audit 
  # @return [PaymentJson]
  describe 'get_payment_by_transaction_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_tags
  # Retrieve payment transaction tags
  # 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :audit 
  # @option opts [BOOLEAN] :included_deleted 
  # @return [Array<TagJson>]
  describe 'get_tags test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notify_state_changed
  # Mark a pending payment transaction as succeeded or failed
  # 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentTransactionJson] :body 
  # @option opts [String] :x_killbill_created_by 
  # @option opts [String] :x_killbill_reason 
  # @option opts [String] :x_killbill_comment 
  # @return [nil]
  describe 'notify_state_changed test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
