=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TestApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TestApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TestApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TestApi' do
    it 'should create an instance of TestApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TestApi)
    end
  end

  # unit tests for get_current_time
  # Get the current time
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :time_zone 
  # @return [ClockResource]
  describe 'get_current_time test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_test_clock_time
  # Set the current time
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :requested_date 
  # @option opts [String] :time_zone 
  # @option opts [Integer] :timeout_sec 
  # @return [ClockResource]
  describe 'set_test_clock_time test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_test_clock_time
  # Move the current time
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :days 
  # @option opts [Integer] :weeks 
  # @option opts [Integer] :months 
  # @option opts [Integer] :years 
  # @option opts [String] :time_zone 
  # @option opts [Integer] :timeout_sec 
  # @return [ClockResource]
  describe 'update_test_clock_time test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for wait_for_queues_to_complete
  # Wait for all available bus events and notifications to be processed
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :timeout_sec 
  # @return [nil]
  describe 'wait_for_queues_to_complete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
