=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::IteratorPlanPhase
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IteratorPlanPhase' do
  before do
    # run before each test
    @instance = SwaggerClient::IteratorPlanPhase.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IteratorPlanPhase' do
    it 'should create an instance of IteratorPlanPhase' do
      expect(@instance).to be_instance_of(SwaggerClient::IteratorPlanPhase)
    end
  end
end

