=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::OverdueJson
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OverdueJson' do
  before do
    # run before each test
    @instance = SwaggerClient::OverdueJson.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OverdueJson' do
    it 'should create an instance of OverdueJson' do
      expect(@instance).to be_instance_of(SwaggerClient::OverdueJson)
    end
  end
  describe 'test attribute "initial_reevaluation_interval"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "overdue_states"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

