=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::SubscriptionUsageRecordJson
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SubscriptionUsageRecordJson' do
  before do
    # run before each test
    @instance = SwaggerClient::SubscriptionUsageRecordJson.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionUsageRecordJson' do
    it 'should create an instance of SubscriptionUsageRecordJson' do
      expect(@instance).to be_instance_of(SwaggerClient::SubscriptionUsageRecordJson)
    end
  end
  describe 'test attribute "subscription_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tracking_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "unit_usage_records"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

