=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module SwaggerClient

  class StaticCatalog
    attr_accessor :effective_date

    attr_accessor :available_base_plan_listings

    attr_accessor :recurring_billing_mode

    attr_accessor :catalog_name

    attr_accessor :current_units

    attr_accessor :current_supported_currencies

    attr_accessor :current_plans

    attr_accessor :current_products

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'effective_date' => :'effectiveDate',
        :'available_base_plan_listings' => :'availableBasePlanListings',
        :'recurring_billing_mode' => :'recurringBillingMode',
        :'catalog_name' => :'catalogName',
        :'current_units' => :'currentUnits',
        :'current_supported_currencies' => :'currentSupportedCurrencies',
        :'current_plans' => :'currentPlans',
        :'current_products' => :'currentProducts'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'effective_date' => :'DateTime',
        :'available_base_plan_listings' => :'Array<Listing>',
        :'recurring_billing_mode' => :'String',
        :'catalog_name' => :'String',
        :'current_units' => :'Array<Unit>',
        :'current_supported_currencies' => :'Array<String>',
        :'current_plans' => :'Array<Plan>',
        :'current_products' => :'Array<Product>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'effectiveDate')
        self.effective_date = attributes[:'effectiveDate']
      end

      if attributes.has_key?(:'availableBasePlanListings')
        if (value = attributes[:'availableBasePlanListings']).is_a?(Array)
          self.available_base_plan_listings = value
        end
      end

      if attributes.has_key?(:'recurringBillingMode')
        self.recurring_billing_mode = attributes[:'recurringBillingMode']
      end

      if attributes.has_key?(:'catalogName')
        self.catalog_name = attributes[:'catalogName']
      end

      if attributes.has_key?(:'currentUnits')
        if (value = attributes[:'currentUnits']).is_a?(Array)
          self.current_units = value
        end
      end

      if attributes.has_key?(:'currentSupportedCurrencies')
        if (value = attributes[:'currentSupportedCurrencies']).is_a?(Array)
          self.current_supported_currencies = value
        end
      end

      if attributes.has_key?(:'currentPlans')
        if (value = attributes[:'currentPlans']).is_a?(Array)
          self.current_plans = value
        end
      end

      if attributes.has_key?(:'currentProducts')
        if (value = attributes[:'currentProducts']).is_a?(Array)
          self.current_products = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      recurring_billing_mode_validator = EnumAttributeValidator.new('String', ["IN_ADVANCE", "IN_ARREAR"])
      return false unless recurring_billing_mode_validator.valid?(@recurring_billing_mode)
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] recurring_billing_mode Object to be assigned
    def recurring_billing_mode=(recurring_billing_mode)
      validator = EnumAttributeValidator.new('String', ["IN_ADVANCE", "IN_ARREAR"])
      unless validator.valid?(recurring_billing_mode)
        fail ArgumentError, "invalid value for 'recurring_billing_mode', must be one of #{validator.allowable_values}."
      end
      @recurring_billing_mode = recurring_billing_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          effective_date == o.effective_date &&
          available_base_plan_listings == o.available_base_plan_listings &&
          recurring_billing_mode == o.recurring_billing_mode &&
          catalog_name == o.catalog_name &&
          current_units == o.current_units &&
          current_supported_currencies == o.current_supported_currencies &&
          current_plans == o.current_plans &&
          current_products == o.current_products
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [effective_date, available_base_plan_listings, recurring_billing_mode, catalog_name, current_units, current_supported_currencies, current_plans, current_products].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
