=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module SwaggerClient

  class Usage
    attr_accessor :usage_type

    attr_accessor :billing_mode

    attr_accessor :tiers

    attr_accessor :blocks

    attr_accessor :billing_period

    attr_accessor :fixed_price

    attr_accessor :recurring_price

    attr_accessor :limits

    attr_accessor :name

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'usage_type' => :'usageType',
        :'billing_mode' => :'billingMode',
        :'tiers' => :'tiers',
        :'blocks' => :'blocks',
        :'billing_period' => :'billingPeriod',
        :'fixed_price' => :'fixedPrice',
        :'recurring_price' => :'recurringPrice',
        :'limits' => :'limits',
        :'name' => :'name'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'usage_type' => :'String',
        :'billing_mode' => :'String',
        :'tiers' => :'Array<Tier>',
        :'blocks' => :'Array<Block>',
        :'billing_period' => :'String',
        :'fixed_price' => :'InternationalPrice',
        :'recurring_price' => :'InternationalPrice',
        :'limits' => :'Array<Limit>',
        :'name' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'usageType')
        self.usage_type = attributes[:'usageType']
      end

      if attributes.has_key?(:'billingMode')
        self.billing_mode = attributes[:'billingMode']
      end

      if attributes.has_key?(:'tiers')
        if (value = attributes[:'tiers']).is_a?(Array)
          self.tiers = value
        end
      end

      if attributes.has_key?(:'blocks')
        if (value = attributes[:'blocks']).is_a?(Array)
          self.blocks = value
        end
      end

      if attributes.has_key?(:'billingPeriod')
        self.billing_period = attributes[:'billingPeriod']
      end

      if attributes.has_key?(:'fixedPrice')
        self.fixed_price = attributes[:'fixedPrice']
      end

      if attributes.has_key?(:'recurringPrice')
        self.recurring_price = attributes[:'recurringPrice']
      end

      if attributes.has_key?(:'limits')
        if (value = attributes[:'limits']).is_a?(Array)
          self.limits = value
        end
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      usage_type_validator = EnumAttributeValidator.new('String', ["CAPACITY", "CONSUMABLE"])
      return false unless usage_type_validator.valid?(@usage_type)
      billing_mode_validator = EnumAttributeValidator.new('String', ["IN_ADVANCE", "IN_ARREAR"])
      return false unless billing_mode_validator.valid?(@billing_mode)
      billing_period_validator = EnumAttributeValidator.new('String', ["DAILY", "WEEKLY", "BIWEEKLY", "THIRTY_DAYS", "MONTHLY", "QUARTERLY", "BIANNUAL", "ANNUAL", "BIENNIAL", "NO_BILLING_PERIOD"])
      return false unless billing_period_validator.valid?(@billing_period)
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] usage_type Object to be assigned
    def usage_type=(usage_type)
      validator = EnumAttributeValidator.new('String', ["CAPACITY", "CONSUMABLE"])
      unless validator.valid?(usage_type)
        fail ArgumentError, "invalid value for 'usage_type', must be one of #{validator.allowable_values}."
      end
      @usage_type = usage_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] billing_mode Object to be assigned
    def billing_mode=(billing_mode)
      validator = EnumAttributeValidator.new('String', ["IN_ADVANCE", "IN_ARREAR"])
      unless validator.valid?(billing_mode)
        fail ArgumentError, "invalid value for 'billing_mode', must be one of #{validator.allowable_values}."
      end
      @billing_mode = billing_mode
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] billing_period Object to be assigned
    def billing_period=(billing_period)
      validator = EnumAttributeValidator.new('String', ["DAILY", "WEEKLY", "BIWEEKLY", "THIRTY_DAYS", "MONTHLY", "QUARTERLY", "BIANNUAL", "ANNUAL", "BIENNIAL", "NO_BILLING_PERIOD"])
      unless validator.valid?(billing_period)
        fail ArgumentError, "invalid value for 'billing_period', must be one of #{validator.allowable_values}."
      end
      @billing_period = billing_period
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          usage_type == o.usage_type &&
          billing_mode == o.billing_mode &&
          tiers == o.tiers &&
          blocks == o.blocks &&
          billing_period == o.billing_period &&
          fixed_price == o.fixed_price &&
          recurring_price == o.recurring_price &&
          limits == o.limits &&
          name == o.name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [usage_type, billing_mode, tiers, blocks, billing_period, fixed_price, recurring_price, limits, name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
