=begin
#Kill Bill

#Kill Bill is an open-source billing and payments platform

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/account_email_json'
require 'swagger_client/models/account_json'
require 'swagger_client/models/account_timeline_json'
require 'swagger_client/models/admin_payment_json'
require 'swagger_client/models/audit_log_json'
require 'swagger_client/models/block'
require 'swagger_client/models/blocking_state_json'
require 'swagger_client/models/bulk_base_subscription_and_add_ons_json'
require 'swagger_client/models/bundle_json'
require 'swagger_client/models/bundle_timeline_json'
require 'swagger_client/models/clock_resource'
require 'swagger_client/models/combo_hosted_payment_page_json'
require 'swagger_client/models/combo_payment_transaction_json'
require 'swagger_client/models/credit_json'
require 'swagger_client/models/custom_field_json'
require 'swagger_client/models/duration'
require 'swagger_client/models/duration_json'
require 'swagger_client/models/event_subscription_json'
require 'swagger_client/models/fixed'
require 'swagger_client/models/hosted_payment_page_fields_json'
require 'swagger_client/models/hosted_payment_page_form_descriptor_json'
require 'swagger_client/models/international_price'
require 'swagger_client/models/invoice_dry_run_json'
require 'swagger_client/models/invoice_email_json'
require 'swagger_client/models/invoice_item_json'
require 'swagger_client/models/invoice_json'
require 'swagger_client/models/invoice_payment_json'
require 'swagger_client/models/invoice_payment_transaction_json'
require 'swagger_client/models/iterable_plugin_property_json'
require 'swagger_client/models/iterator_plan_phase'
require 'swagger_client/models/limit'
require 'swagger_client/models/listing'
require 'swagger_client/models/node_command_json'
require 'swagger_client/models/node_command_property_json'
require 'swagger_client/models/overdue_condition_json'
require 'swagger_client/models/overdue_json'
require 'swagger_client/models/overdue_state_config_json'
require 'swagger_client/models/overdue_state_json'
require 'swagger_client/models/payment_attempt_json'
require 'swagger_client/models/payment_json'
require 'swagger_client/models/payment_method_json'
require 'swagger_client/models/payment_method_plugin_detail_json'
require 'swagger_client/models/payment_transaction_json'
require 'swagger_client/models/phase_price_override_json'
require 'swagger_client/models/plan'
require 'swagger_client/models/plan_detail_json'
require 'swagger_client/models/plan_phase'
require 'swagger_client/models/plugin_info_json'
require 'swagger_client/models/plugin_property_json'
require 'swagger_client/models/plugin_service_info_json'
require 'swagger_client/models/price'
require 'swagger_client/models/price_json'
require 'swagger_client/models/price_list'
require 'swagger_client/models/product'
require 'swagger_client/models/recurring'
require 'swagger_client/models/role_definition_json'
require 'swagger_client/models/rolled_up_unit_json'
require 'swagger_client/models/rolled_up_usage_json'
require 'swagger_client/models/session_json'
require 'swagger_client/models/simple_plan_json'
require 'swagger_client/models/static_catalog'
require 'swagger_client/models/subject_json'
require 'swagger_client/models/subscription_json'
require 'swagger_client/models/subscription_usage_record_json'
require 'swagger_client/models/tag_definition_json'
require 'swagger_client/models/tag_json'
require 'swagger_client/models/tenant_json'
require 'swagger_client/models/tenant_key_json'
require 'swagger_client/models/tier'
require 'swagger_client/models/tiered_block'
require 'swagger_client/models/unit'
require 'swagger_client/models/unit_usage_record_json'
require 'swagger_client/models/usage'
require 'swagger_client/models/usage_record_json'
require 'swagger_client/models/user_roles_json'

# APIs
require 'swagger_client/api/accounts_api'
require 'swagger_client/api/admin_api'
require 'swagger_client/api/bundles_api'
require 'swagger_client/api/catalog_api'
require 'swagger_client/api/credits_api'
require 'swagger_client/api/custom_fields_api'
require 'swagger_client/api/export_api'
require 'swagger_client/api/invoice_payments_api'
require 'swagger_client/api/invoices_api'
require 'swagger_client/api/nodes_info_api'
require 'swagger_client/api/overdue_api'
require 'swagger_client/api/payment_gateways_api'
require 'swagger_client/api/payment_methods_api'
require 'swagger_client/api/payment_transactions_api'
require 'swagger_client/api/payments_api'
require 'swagger_client/api/plugins_info_api'
require 'swagger_client/api/security_api'
require 'swagger_client/api/subscriptions_api'
require 'swagger_client/api/tag_definitions_api'
require 'swagger_client/api/tags_api'
require 'swagger_client/api/tenants_api'
require 'swagger_client/api/test_api'
require 'swagger_client/api/usages_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
